const $=s=>document.querySelector(s);
const randomToken=()=>{const bytes=crypto.getRandomValues(new Uint8Array(24));return btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');};
const uuid=()=>crypto.randomUUID?.()||'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const n=crypto.getRandomValues(new Uint8Array(1))[0]&15;return(c==='x'?n:(n&3)|8).toString(16);});
const labels={uploading:'Uploading your photo',voice_ready:'Creating the voice',voice_submitting:'Creating the voice',voice_pending:'Creating the voice',measuring:'Creating the voice',audio_ready:'Animating your photo',video_submitting:'Animating your photo',video_pending:'Animating your photo',saving:'Saving your video',ready:'Ready',failed:'We couldn’t finish this video.',review:'This generation needs a check.'};
export function initVideoBuilder(config,analytics){
 const settings=config.video||{available:false,notice:'Video generation is not available yet.'};let photo=null,job=null,attempt=null,busy=false,pollTimer,photoVersion=0;
 const scratch=$('#scratch-builder'),video=$('#video-builder'),tabs=[$('#scratch-tab'),$('#video-tab')];
 const status=text=>$('#video-status').textContent=text;
 function tab(which){scratch.hidden=which==='video';video.hidden=which!=='video';document.body.classList.toggle('video-mode',which==='video');tabs.forEach((t,i)=>{const chosen=i===(which==='video'?1:0);t.setAttribute('aria-selected',String(chosen));t.tabIndex=chosen?0:-1;});if(which==='scratch')$('#video-player').pause();}
 tabs.forEach((t,i)=>{t.addEventListener('click',()=>tab(i?'video':'scratch'));t.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?1:1-i;tabs[next].focus();tab(next?'video':'scratch');}});});
 $('#video-availability').textContent=settings.mocked?'TEST FIXTURE — no provider generation or charges.':settings.notice||'';
 function persist(){try{localStorage.setItem('fig-video-draft',JSON.stringify({action:$('#video-action').value,message:$('#video-message').value,to:$('#video-to').value,from:$('#video-from').value,photo:attempt?.id?null:photo,attempt}));return true;}catch{status('Your browser cannot save this draft for refresh. Keep this tab open until your video is ready.');return false;}}
 function update(){$('#video-remove-photo').hidden=!photo;const name=$('#video-to').value.trim();$('#video-cover').textContent=name?`This one’s for you, ${name}.`:'This one’s for you.';const message=$('#video-message').value.trim(),count=message?message.split(/\s+/u).length:0;$('#video-word-count').textContent=`${count}/20 words · 10 seconds max`;$('#video-generate').disabled=busy||!settings.available||!photo||!$('#video-action').value.trim()||!message||count>20||message.length>200||!$('#video-to').value.trim()||!$('#video-from').value.trim();for(const b of document.querySelectorAll('[data-video-action]'))b.setAttribute('aria-pressed',String(b.dataset.videoAction===$('#video-action').value.trim()));persist();}
 async function addPhoto(file){if(!file)return;const version=++photoVersion;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>2*1024*1024){status('Choose one JPG, PNG or WebP photo under 2 MB.');return;}try{const bitmap=await createImageBitmap(file);const area=bitmap.width*bitmap.height;bitmap.close();if(area>20000000)throw Error('Choose a photo under 20 megapixels.');const value=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Could not read this photo.'));r.readAsDataURL(file);});if(version!==photoVersion)return;photo=value;$('#video-photo-preview').src=photo;$('#video-photo-preview').hidden=false;$('#video-empty').hidden=true;$('#video-photo-name').textContent='Photo added ✓';status('');update();}catch(e){status(e.message);}}
 $('#video-remove-photo').addEventListener('click',()=>{photoVersion++;photo=null;attempt=null;$('#video-photo').value='';$('#video-photo-preview').removeAttribute('src');$('#video-photo-preview').hidden=true;$('#video-empty').hidden=false;$('#video-photo-name').textContent='Choose or drop a photo';status('');update();});
 $('#video-photo').addEventListener('change',e=>addPhoto(e.target.files[0]));const drop=$('#video-dropzone');drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('is-dragging');});drop.addEventListener('dragleave',()=>drop.classList.remove('is-dragging'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('is-dragging');if(e.dataTransfer.files.length!==1){status('Add one photo at a time.');return;}addPhoto(e.dataTransfer.files[0]);});
 for(const id of ['video-action','video-message','video-to','video-from'])$('#'+id).addEventListener('input',update);for(const b of document.querySelectorAll('[data-video-action]'))b.addEventListener('click',()=>{$('#video-action').value=b.dataset.videoAction;update();});
 async function request(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(attempt?{Authorization:`Bearer ${attempt.token}`}:{})}});const data=await r.json();if(!r.ok)throw Object.assign(Error(data.error||'Please try again.'),{status:r.status});return data;}
 function showJob(next){job=next;$('#video-action').value=job.action||'';$('#video-message').value=job.message;$('#video-to').value=job.to||'';$('#video-from').value=job.from||'';$('#video-draft').hidden=true;$('#video-progress').hidden=job.state==='ready';$('#video-finished').hidden=job.state!=='ready';$('#video-failed-edit').hidden=!job.retryAllowed||job.state==='ready';$('#video-stage').textContent=labels[job.state]||'Checking your video';status(job.error||'');$('#video-check').hidden=['ready','failed','review'].includes(job.state);persist();
  if(job.state==='ready'){$('#video-player').src=job.videoUrl;$('#video-player').hidden=false;$('#video-photo-preview').hidden=true;$('#video-empty').hidden=true;$('#video-preview-note').textContent=job.message;$('#video-link').value=job.shareUrl;$('#video-download').href=job.videoUrl+'?download=1';$('#video-share').hidden=!navigator.share;}

 }
 async function loadPhoto(){if(photo||!job)return;try{const r=await fetch(job.photoUrl,{headers:{Authorization:`Bearer ${attempt.token}`}});if(!r.ok)return;photo=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);r.blob().then(blob=>reader.readAsDataURL(blob));});$('#video-photo-preview').src=photo;$('#video-photo-preview').hidden=job.state==='ready';$('#video-empty').hidden=true;}catch{}}
 async function check(){clearTimeout(pollTimer);if(!attempt?.id)return;try{showJob(await request(`/api/video/jobs/${attempt.id}/advance`,{method:'POST',body:'{}'}));await loadPhoto();}catch(e){status('Your generation can be resumed. Check again in a moment.');}if(job&&!['ready','failed','review'].includes(job.state))pollTimer=setTimeout(check,6000);}
 $('#video-check').addEventListener('click',check);
 $('#video-form').addEventListener('submit',async e=>{e.preventDefault();if(busy||$('#video-generate').disabled)return;busy=true;status('Uploading your photo');update();
  attempt=attempt||{key:uuid(),token:randomToken()};persist();
  try{const next=await request('/api/video/jobs',{method:'POST',body:JSON.stringify({photo,action:$('#video-action').value,message:$('#video-message').value,to:$('#video-to').value,from:$('#video-from').value,idempotencyKey:attempt.key,resumeToken:attempt.token,analytics:analytics.creation()})});attempt.id=next.id;showJob(next);pollTimer=setTimeout(check,1800);}
  catch(error){status(error.message);/* Keep the same key after uncertain network errors. */if(error.status&&error.status!==503)attempt=null;}
  finally{busy=false;update();}
 });
 async function edit(){clearTimeout(pollTimer);await loadPhoto();attempt=null;job=null;$('#video-player').pause();$('#video-player').hidden=true;$('#video-photo-preview').hidden=!photo;$('#video-draft').hidden=false;$('#video-progress').hidden=true;$('#video-finished').hidden=true;$('#video-failed-edit').hidden=true;$('#video-preview-note').textContent='Your video will appear here.';status('');update();}
 $('#video-edit').addEventListener('click',edit);$('#video-failed-edit').addEventListener('click',edit);
 async function copy(){try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(job.shareUrl);else{const input=$('#video-link');input.focus();input.select();if(!document.execCommand('copy'))throw Error();}status('Link copied. Ready to send.');}catch{const input=$('#video-link');input.focus();input.select();status('Select and copy your link to share.');}analytics.event('video_shared');}
 $('#video-copy').addEventListener('click',copy);$('#video-share').addEventListener('click',async()=>{try{await navigator.share({title:'You’ve got a surprise — SendFiggle',text:'A little surprise, delivered.',url:job.shareUrl});analytics.event('video_shared');}catch(e){if(e.name!=='AbortError')await copy();}});$('#video-player').addEventListener('play',()=>analytics.event('video_played',{},true));
 try{const saved=JSON.parse(localStorage.getItem('fig-video-draft'));if(saved){$('#video-action').value=saved.action||'';$('#video-message').value=saved.message||'Thinking of you. Hope this makes you smile.';$('#video-to').value=saved.to||'';$('#video-from').value=saved.from||'';photo=saved.photo||null;attempt=saved.attempt||null;if(photo){$('#video-photo-preview').src=photo;$('#video-photo-preview').hidden=false;$('#video-empty').hidden=true;$('#video-photo-name').textContent='Photo added ✓';}if(attempt?.id){tab('video');check();}else if(attempt&&photo&&settings.available){tab('video');queueMicrotask(()=>$('#video-form').requestSubmit());}}}catch{}
 update();
}
export function renderRecipientVideo(card,analytics){
 $('#scratch-panel').hidden=true;$('#preview').hidden=true;document.body.classList.add('video-recipient');
 const region=document.createElement('div');region.className='recipient-video';const player=document.createElement('video');player.controls=true;player.playsInline=true;player.preload='none';player.src=card.video;player.setAttribute('aria-label','Your video greeting');
 const play=document.createElement('button');play.id='recipient-video-play';play.className='primary';play.textContent='Play video';play.addEventListener('click',()=>{player.play().catch(()=>{});});
 player.addEventListener('play',()=>{play.hidden=true;analytics.event('video_played',{},true);});const note=document.createElement('p');note.textContent=card.message;note.className='video-transcript';const label=document.createElement('p');label.className='video-help';label.textContent='AI-generated video and synthetic voice.';const signature=document.createElement('p');signature.className='video-signature';signature.textContent=card.from?`From ${card.from}`:'';region.append(player,play,note,signature,label);$('#scratch-panel').after(region);
}
